# Generated by Django 2.2 on 2020-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
