# Generated by Django 2.2 on 2020-04-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_story_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='votes',
        ),
    ]
